-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_REFUND_REQUESTED';
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_REFUND_SUCCEEDED';
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_REFUND_FAILED';
