-- AlterEnum
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_WEBHOOK_RECEIVED';
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_WEBHOOK_PROCESSED';
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_WEBHOOK_IGNORED';
ALTER TYPE "AuditEventType" ADD VALUE 'STRIPE_REFUND_STATUS_UPDATED';
